Logic
Rim-777/ElixirCourseHomeWork-4 pull request #1
Opened 2024-03-01 12:33 UTC by Rim-777

2024-03-02 05:39 UTC, am-kantox requested changes
There are two things:

- always prefer asynch over synch whenever possible
- don’t do checks and validations outside of the process, whenever possible

The process always knows better, what to do, delegate it.

2024-03-02 05:39 UTC, am-kantox commented on lib/tram/state_machine.ex
> +  def on_transition({:unlaunched, :launched} = transition) do
This is not a callback, this is an interface, so it should be named `transition` or even `transit`.

2024-03-02 05:39 UTC, am-kantox commented on lib/tram/state_machine.ex
> +    case current_tram_state() do
This is what you want to improve. You fight the actor model to make it quack and walk like the OOP. Instead, you might make it your friend. 

You don’t need to explicitly query the state, which makes the code ① synchronous for no reason, and ② clumsy. Remember, inside `GenServer` callbacks you _have the state at fingers_.

That being said, instead of doing
```elixir
def transition(from, to) do
  case GenServer.call(:state) do
    ^from -> GenServer.call(:move, to)
  end
end
```
that involves two synchronous calls and partially reimplements the existing functionality, one might do
```elixir
def transition(from, to), do: GenServer.cast({:transition, from, to)

@impl GenServer
# this clause makes sure we _can_ transition, see `from` in transition _and_ in state
def handle_cast({:transition, from, to}, from) when to in […] do
  {:noreply, to}
end
# transition is still possible for this state but not allowed
def handle_cast({:transition, from, to}, from) do
  Logger.warning("State #{to} is unreachable from #{from}")
  {:noreply, from}
end
def handle_cast({:transition, from, to}, current) do
  Logger.warning("Requested transition #{from} → #{to} but current is #{current}")
  {:noreply, current}
end
```

2024-03-04 21:16 UTC, Rim-777 commented on test/tram/state_machine_test.exs
> +    ) =~ "Abracadabra"
I couldn't find how to make it working

2024-03-05 06:31 UTC, am-kantox approved these changes
:zap: :droplet: :zap: :gem: :zap: :blue_heart: :zap:

All is absolutely good, save for when you ignore the state where it might be used to tighten the clause to never leak the incorrect state into.

In general, if you find yourself not using the state, this is most likely a signal of you are doing something wrong.

2024-03-05 06:31 UTC, am-kantox commented on lib/tram/state_machine.ex
> +  def transit(from, _to) when from not in @applicable_states do
There are two ways to deal with enum-like arguments. One can define _applicable_ and then allow anything else. I prefer another one: match applicables directly and then use “catch-all” clause. That said, instead of 
```elixir
def foo(state) when state not in [:good1, :good2], do: :error
def foo(state), do: {:ok, do_smth()}
```
use
```elixir
def foo(:good1), do: {:ok, do_smth_1()}
def foo(:good2), do: {:ok, do_smth_2()}
def foo(_state), do: :error
```

2024-03-05 06:31 UTC, am-kantox commented on lib/tram/state_machine.ex
> +  def handle_cast({:transition, from, to}, %{current_state: current} = state)
The same as above.
```elixir
#                             ⇓⇓⇓⇓                        ⇓⇓⇓⇓
def handle_cast({:transition, from, to}, %{current_state: from}), do: {:ok, do_smth()}
def handle_cast({:transition, from, to}, %{current_state: _}), do: {:error, "not in #{from}"}
```

2024-03-05 06:31 UTC, am-kantox commented on lib/tram/state_machine.ex
> +  def handle_cast({:transition, from, to}, state) when to == from do
```suggestion
  def handle_cast({:transition, from_to, from_to}, state) do
```

2024-03-05 06:31 UTC, am-kantox commented on lib/tram/state_machine.ex
> +    Logger.warning("Stop raping the tram!!!")
🤣

2024-03-05 06:31 UTC, am-kantox commented on lib/tram/state_machine.ex
> +  def handle_cast({:transition, :unlaunched, :launched}, _state) do
```suggestion
  def handle_cast({:transition, :unlaunched, :launched}, %{current_state: :unlaunched} = state) do
```

2024-03-05 06:31 UTC, am-kantox commented on lib/tram/state_machine.ex
> +  def handle_cast({:transition, :launched, to}, _state) when to in [:unlaunched, :moving] do
I have a gut feeling that `:launched` and `:moving` have basically the same semantics.

2024-03-05 06:31 UTC, am-kantox commented on test/tram/state_machine_test.exs
> +    ) =~ "Abracadabra"
[`capture_log/1`](https://hexdocs.pm/ex_unit/ExUnit.CaptureLog.html#capture_log/2) docs explicitly states:

> It is possible to ensure explicit log messages from other processes are captured by waiting for their exit or monitor signal.

`Logger` is fully asynchronous. One cannot expect logs to be printed by the exit of this function. You might hack by monitoring the process as suggested in the docs, but I’d better list it in the unresolved questions and wait until we get to real-life thorough testing of distributed stuff.

2024-03-05 10:38 UTC, Rim-777 commented on lib/tram/state_machine.ex
> +  def transit(from, _to) when from not in @applicable_states do
Thank you, @am-kantox, but what would you recommend if we want to explicitly point out a specific inapplicable argument from 2? In our case, we have `from` and `to` and the “catch-all” clause will show some of them.

2024-03-05 13:27 UTC, Rim-777 commented on lib/tram/state_machine.ex
> +  def transit(from, _to) when from not in @applicable_states do
But we have 2 arguments, how does the` catch-all` clause distinguish which particular argument is bad and explicitly say it in the warning message `:ufo` is an alien  👽 and :good is a correct arg?

def foo(:ufo, :good), do: {:error, ":ufo is a scarry alien"}

2024-03-05 13:40 UTC, am-kantox commented on lib/tram/state_machine.ex
> +  def transit(from, _to) when from not in @applicable_states do
```elixir
# success path
def foo(ufo, _good) when is_scary_alien(ufo),
  do: {:error, "ufo is a scary alien"}
def foo(_, _),
  do: {:error, "we are doomed"}

```

2024-03-05 14:06 UTC, Rim-777 commented on lib/tram/state_machine.ex
> +  def transit(from, _to) when from not in @applicable_states do
Then I still can't understand how does `foo(ufo, _good) when is_scary_alien(ufo)` differs from 
`def transit(from, _to) when from not in @applicable_states do`

2024-03-05 14:23 UTC, Rim-777 commented on lib/tram/state_machine.ex
> +  def transit(from, _to) when from not in @applicable_states do
fixed, could you please confirm now looks good?

2024-03-05 14:28 UTC, am-kantox commented on lib/tram/state_machine.ex
> +  def transit(from, _to) when from not in @applicable_states do
Exactly. First go clauses with clean logic (success path.)

Then error handling, and in production you can safely remove all but one, leaving just error happened, here are arguments, here is the state.

If they went in the beginning, removing them would requiere refactoring.

2024-03-05 14:29 UTC, am-kantox commented on lib/tram/state_machine.ex
> +  def transit(from, _to) when from not in @applicable_states do
> fixed, could you please confirm now looks good? 

Looks good!

2024-03-05 14:32 UTC, Rim-777 commented on lib/tram/state_machine.ex
> +  def transit(from, _to) when from not in @applicable_states do
Makes sense, thank you!

2024-03-05 14:44 UTC, merged